# Generated by Django 4.2.11 on 2026-05-20 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom de la démarche')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(verbose_name='Description et instructions')),
                ('stamp_duty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Frais de timbre (FCFA)')),
                ('estimated_processing_time', models.CharField(blank=True, max_length=50, verbose_name='Délai estimé')),
                ('is_active', models.BooleanField(default=True, verbose_name='Disponible en ligne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Démarche Administrative',
                'verbose_name_plural': 'Démarches Administratives',
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis / En attente de revue'), ('IN_PROGRESS', 'En cours de traitement'), ('APPROVED', 'Approuvé / Prêt pour retrait'), ('REJECTED', 'Rejeté / Motif fourni')], default='SUBMITTED', max_length=20, verbose_name='Statut du dossier')),
                ('tracking_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de suivi')),
                ('agent_notes', models.TextField(blank=True, verbose_name="Notes de l'administration")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_requests', to=settings.AUTH_USER_MODEL, verbose_name='Citoyen')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='services.administrativeservice', verbose_name='Service demandé')),
            ],
            options={
                'verbose_name': 'Dossier de Demande',
                'verbose_name_plural': 'Dossiers de Demandes',
                'ordering': ['-created_at'],
            },
        ),
    ]
