# Generated by Django 4.2.11 on 2026-05-20 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrequest',
            options={'verbose_name': "Demande d'utilisateur", 'verbose_name_plural': "Demandes d'utilisateurs"},
        ),
        migrations.AddField(
            model_name='userrequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=services.models.user_directory_path, verbose_name='Document justificatif'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='agent_notes',
            field=models.TextField(blank=True, null=True, verbose_name="Notes de l'agent"),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.administrativeservice'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Soumis'), ('IN_PROGRESS', 'En cours de traitement'), ('VALIDATED', 'Validé'), ('REJECTED', 'Rejeté')], default='SUBMITTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='tracking_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
